apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"{{- .Values.service.port }}":{"name": "{{- .Values.gkeNeg.name }}"}}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.portName }}
      protocol: TCP
      targetPort: {{ .Values.service.portName }}
  selector:
    {{- include "app.runLabels" . | nindent 4 }}
