replicaCount: 3

image:
  repository: ccr.ccs.tencentyun.com/wumengye/dubbo-go-server
  pullPolicy: Always
  tag: "1.0.10"

# Dubbo-go-mesh version control labels
version:
  labels:
    dubbogoAppVersion: v1

container:
  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  ports:
    - name: triple
      containerPort: 20000
      protocol: TCP
  resources: {}
  volumeMounts: {}

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 20000
  portName: triple

gkeNeg:
  name: dubbogo-helloworld-service-neg